BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB
BBBBB BBBBBXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
    BBBBBB
  XXXXXX
XXXXXX
BBBBBBBB BBBBBBB
