BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBB

BBBBB BBBBBBB
  XXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
    BBBBBBBBBB
    FFFFFF
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX
BBBBBBBB
