
BBBB BBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBB
    
BBBB
    BB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBB XXXBBBBBXX
        BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XX
        BBBBB
    BBBBB
    XBB BBBBBBBXXXBBBBB XXXXXXXXX BB BBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBB XXXBBBBBBBBBXXXXXXXXXXXXXXXBBBBBBB BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB XXXXXXXXXXBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBXX
        BB BBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
                FFFFBB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXXXX
        BBBBB

        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBB

        BB BBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBB

        BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
                XXXXXX XXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
                    BBBBBBBBBBBB BBBBB
                    FFFF
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXX
            BBBB
                XXXX XXXXXXXXX
                    BBBBBBBBBBBB BBBBB
                XXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBB
        BBBBB
    XXBB BBBBBBBXXXBBBBBX
    BB BBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBB
            XXXXXX
        BBBBB
        XXXXXX
    BBBBB
BBBBB
