# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-09 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='sign_button_text',
            field=models.CharField(default='Sign', max_length=50),
        ),
    ]
