# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_petition_sign_button_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='permissiondefinition',
            options={'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AddField(
            model_name='permission',
            name='value',
            field=models.BooleanField(default=False, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
