# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('petitions', '0003_auto_20170410_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='ask_email',
            field=models.BooleanField(default=False, verbose_name='Ask about e-mail'),
        ),
        migrations.AddField(
            model_name='signature',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='ask_city',
            field=models.BooleanField(default=True, verbose_name='Ask about city'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Second name'),
        ),
    ]
