# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 00:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0002_initial_data'),
        ('petitions', '0005_auto_20170411_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign',
                                    verbose_name='Campaign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petition',
            name='paginate_by',
            field=models.SmallIntegerField(default=50,
                                           help_text='Specifies the number of signatures per signatures page',
                                           verbose_name='Paginate signatures by'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='sign_button_text',
            field=models.CharField(default='Sign', help_text='Sign button text', max_length=50),
        ),
        migrations.AlterField(
            model_name='petition',
            name='slug',
            field=models.CharField(help_text='Modify to update address of petition', max_length=50, unique=True,
                                   verbose_name='Slug'),
        ),
    ]
