# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0006_auto_20170412_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='overview',
            field=models.TextField(default='', verbose_name='Overview'),
            preserve_default=False,
        ),
    ]
