# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


def update_signature_counter(apps, schema_editor):
    Petition = apps.get_model('petitions', 'Petition')
    for petition in Petition.objects.all():
        for i, signature in enumerate(petition.signature_set.all()):
            signature.counter = i + 1
            signature.save(update_fields=['counter'])


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0008_auto_20170412_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='counter',
            field=models.SmallIntegerField(default=0, verbose_name='No.'),
            preserve_default=False,
        ),
        migrations.RunPython(update_signature_counter)
    ]
