# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0009_signature_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='disabled_message',
            field=models.TextField(default='The ability to sign under this petition has been disabled.', help_text='A message posted on the page if the signature is disabled.', verbose_name='Text of disabled signature message'),
        ),
        migrations.AddField(
            model_name='petition',
            name='disabled_warning',
            field=models.TextField(default='The ability to sign under this petition has been disabled.', help_text='A message when someone is trying to inject a signature, despite turning off the form.', verbose_name='Message of disabled signature warning'),
        ),
    ]
