# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


def update_theme_forward(apps, schema_editor):
    Theme = apps.get_model('themes', 'Theme')
    Theme.objects.update_or_create(
        id=1,
        defaults={
            'name': 'Niezależne fundusze norweskie',
            'description': '',
            'authorship': 'Kamil Breguła (mik-laj)',
            'prefix': 'norweskie',
        }
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Name')),
                ('authorship', models.CharField(max_length=100, verbose_name='Authorship')),
                ('prefix', models.CharField(max_length=25, verbose_name='System name of theme prefix')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name_plural': 'Themes',
                'verbose_name': 'Theme',
            },
        ),
        migrations.RunPython(update_theme_forward)
    ]
