# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Show title of petition'),
        ),
    ]
