# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0003_campaign_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(help_text='Users responsive to manage of campaign',
                                         to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
