# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20170412_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='site',
            field=models.ForeignKey(help_text='Sites used in campaign', on_delete=django.db.models.deletion.CASCADE, to='sites.Site', unique=True, verbose_name='Site'),
        ),
    ]
