# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20170416_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='site',
            field=models.OneToOneField(help_text='Sites used in campaign', on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
    ]
