# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20170416_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='site',
            field=models.ForeignKey(help_text='Sites used in campaign', on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
    ]
