BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBB
  XXXXXX
XXXXXX
BBBBBBBB
