BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Set Password') BBBBBBBB

BBBBB BBBBB
    XXXX gettext(u'Set Password') XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Set Password') XXX
    XXXXXXX
BBBBBBBB

