BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Change Password') BBBBBBBB

BBBBB BBBBB
    XXXX gettext(u'Change Password') XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Change Password') XXXXXXXXX
    XXXXXXX
BBBBBBBB

