BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Signup') BBBBBBBB

BBBBB BBBBB
XXXX gettext(u'Sign Up') XXXXX

XXX gettext(u'Already have an account? Then please <a href="%(login_url)s">sign in</a>.') SSSSSSS SSSS SS SSSSSSSS SSSS SSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSXXXX

XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
  BBBBBBBBBB
  FFFFFF
  BB BBBBBBBBBBBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
  BBBBB
  XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Sign Up')  XXXXXXXXXXXXXXXX
XXXXXXX

BBBBBBBB

